import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuditPreviewComponent, DelegationPreviewComponent, PrioritiesPreviewComponent, SettingsPreviewComponent, StatisticsPreviewComponent } from './feature-previews.component';

type ViewKey = 'dashboard' | 'mapa' | 'reportes' | 'delegacion' | 'prioridades' | 'estadisticas' | 'configuracion' | 'auditoria';
type Status = 'Pendiente' | 'En proceso' | 'Resuelto';
type Priority = 'Crítica' | 'Alta' | 'Media' | 'Baja';

interface Report { id: string; title: string; category: string; zone: string; priority: Priority; status: Status; owner: string; age: string; tone: string; x: number; y: number; }

@Component({
  selector: 'mu-root', standalone: true, imports: [CommonModule, FormsModule, AuditPreviewComponent, DelegationPreviewComponent, PrioritiesPreviewComponent, SettingsPreviewComponent, StatisticsPreviewComponent],
  template: `
    <div class="app-shell">
      <aside class="sidebar" [class.collapsed]="sidebarCollapsed" [class.mobile-open]="mobileMenuOpen">
        <div class="brand"><span class="brand-mark">⌖</span><span class="brand-name">Mapa <b>Urbano</b></span><button class="collapse" (click)="sidebarCollapsed = !sidebarCollapsed" aria-label="Contraer menú">{{ sidebarCollapsed ? '›' : '‹' }}</button></div>
        <div class="workspace-label">OPERACIONES</div>
        <nav class="nav-list" aria-label="Navegación principal">
          <button *ngFor="let item of navItems" [class.active]="currentView === item.key" (click)="setView(item.key)" [title]="item.label"><span class="nav-icon">{{ item.icon }}</span><span>{{ item.label }}</span><span *ngIf="item.badge" class="nav-badge">{{ item.badge }}</span></button>
        </nav>
        <div class="sidebar-bottom"><div class="help-card"><span class="help-icon">?</span><div><b>¿Necesitás ayuda?</b><small>Ver guía del panel</small></div></div><button class="user-card"><span class="avatar">MG</span><span class="user-copy"><b>María González</b><small>Supervisora</small></span><span class="dots">•••</span></button></div>
      </aside><button *ngIf="mobileMenuOpen" class="mobile-overlay" (click)="mobileMenuOpen=false" aria-label="Cerrar menú"></button>

      <main class="main-content">
        <header class="topbar"><div class="breadcrumbs"><button class="mobile-menu-button" (click)="mobileMenuOpen=true" aria-label="Abrir menú">☰</button><span>Operaciones</span><span class="slash">/</span><b>{{ activeLabel }}</b></div><div class="top-actions"><button class="icon-button" aria-label="Buscar">⌕</button><button class="icon-button notification" aria-label="Notificaciones">♢<span></span></button><div class="live-status"><i></i> Sistema operativo</div><button class="top-avatar">MG</button></div></header>
        <section class="page-content" [class.detail-open]="selectedReport">
          <div class="page-heading"><div><p class="eyebrow">Jueves, 27 de agosto de 2026</p><h1>{{ activeTitle }}</h1><p class="subtitle">Monitoreá y coordiná la atención de los problemas urbanos de la ciudad.</p></div><button class="primary-button" (click)="showToast('Nuevo reporte: formulario próximamente conectado')"><span>＋</span> Nuevo reporte</button></div>

          <ng-container [ngSwitch]="currentView">
            <section *ngSwitchCase="'dashboard'" class="view-grid">
              <div class="kpi-grid"><article class="kpi-card"><div class="kpi-top"><span class="kpi-label">Reportes activos</span><span class="kpi-icon teal">⌁</span></div><strong>248</strong><small class="trend up">↗ 12,4% <em>vs. mes anterior</em></small></article><article class="kpi-card"><div class="kpi-top"><span class="kpi-label">Sin asignar</span><span class="kpi-icon coral">!</span></div><strong>37</strong><small class="trend down">↘ 8,1% <em>vs. semana anterior</em></small></article><article class="kpi-card"><div class="kpi-top"><span class="kpi-label">En proceso</span><span class="kpi-icon amber">◷</span></div><strong>126</strong><small class="trend up">↗ 6,2% <em>vs. mes anterior</em></small></article><article class="kpi-card"><div class="kpi-top"><span class="kpi-label">Resueltos este mes</span><span class="kpi-icon blue">✓</span></div><strong>84</strong><small class="trend up">↗ 18,7% <em>vs. mes anterior</em></small></article></div>
              <div class="main-columns"><article class="panel map-panel"><div class="panel-header"><div><h2>Vista general</h2><p>Reportes activos por ubicación</p></div><button class="ghost-button" (click)="setView('mapa')">Abrir mapa <span>↗</span></button></div><div class="map-canvas"><div class="map-label label-one">Centro</div><div class="map-label label-two">Godoy Cruz</div><div class="map-label label-three">Ciudad</div><div class="road road-a"></div><div class="road road-b"></div><div class="road road-c"></div><div class="river"></div><button *ngFor="let report of reports" class="map-pin" [style.left.%]="report.x" [style.top.%]="report.y" [class]="'pin-' + report.tone" (click)="selectReport(report)" [attr.aria-label]="report.title">●</button><div class="map-legend"><span><i class="dot critical"></i> Crítica</span><span><i class="dot high"></i> Alta</span><span><i class="dot normal"></i> Normal</span></div></div></article><article class="panel priority-panel"><div class="panel-header"><div><h2>Atención prioritaria</h2><p>Requieren seguimiento hoy</p></div><button class="more-button">•••</button></div><div class="priority-list"><button *ngFor="let report of priorityReports" class="priority-row" (click)="selectReport(report)"><span class="priority-line" [class]="'line-' + report.tone"></span><span class="priority-content"><b>{{ report.title }}</b><small>{{ report.category }} · {{ report.zone }}</small></span><span class="priority-arrow">›</span></button></div><button class="view-all" (click)="setView('prioridades')">Ver todas las prioridades <span>→</span></button></article></div>
              <article class="panel reports-panel"><div class="panel-header"><div><h2>Reportes recientes</h2><p>Últimas actualizaciones de la comunidad</p></div><button class="ghost-button" (click)="setView('reportes')">Ver todos <span>→</span></button></div><div class="table-wrap"><table><thead><tr><th>REPORTE</th><th>CATEGORÍA</th><th>ZONA</th><th>PRIORIDAD</th><th>ESTADO</th><th>RESPONSABLE</th><th></th></tr></thead><tbody><tr *ngFor="let report of reports.slice(0, 5)" (click)="selectReport(report)"><td><div class="report-name"><span class="report-id">{{ report.id }}</span><b>{{ report.title }}</b><small>Hace {{ report.age }}</small></div></td><td><span class="category"><i [class]="'cat-' + report.tone"></i>{{ report.category }}</span></td><td>{{ report.zone }}</td><td><span class="priority-tag" [class]="'priority-' + report.tone">{{ report.priority }}</span></td><td><span class="status-tag" [class]="statusClass(report.status)"><i></i>{{ report.status }}</span></td><td><span class="owner"><span class="mini-avatar">{{ initials(report.owner) }}</span>{{ report.owner }}</span></td><td><span class="row-more">•••</span></td></tr></tbody></table></div></article>
            </section>
            <section *ngSwitchCase="'delegacion'" class="module-view"><mu-delegation-preview /></section>
            <section *ngSwitchCase="'prioridades'" class="module-view"><mu-priorities-preview /></section>
            <section *ngSwitchCase="'estadisticas'" class="module-view"><mu-statistics-preview /></section>
            <section *ngSwitchCase="'configuracion'" class="module-view"><mu-settings-preview /></section>
            <section *ngSwitchCase="'auditoria'" class="module-view"><mu-audit-preview /></section>
            <section *ngSwitchDefault class="module-view"><div class="module-toolbar"><div class="search-field">⌕ <input placeholder="Buscar reportes..." [(ngModel)]="searchTerm" aria-label="Buscar reportes"></div><button class="filter-button">☷ Filtros <span class="filter-count">3</span></button><button class="ghost-button">Exportar ↓</button></div><div class="module-summary"><div><b>{{ currentView === 'mapa' ? 'Mapa de reportes' : activeTitle }}</b><span>{{ filteredReports.length }} resultados encontrados</span></div><div class="view-switch"><button class="selected">▦</button><button>☷</button></div></div><div *ngIf="currentView === 'mapa'" class="large-map map-canvas"><div class="map-label label-one">Centro</div><div class="map-label label-two">Godoy Cruz</div><div class="map-label label-three">Ciudad</div><div class="road road-a"></div><div class="road road-b"></div><div class="road road-c"></div><div class="river"></div><button *ngFor="let report of filteredReports" class="map-pin" [style.left.%]="report.x" [style.top.%]="report.y" [class]="'pin-' + report.tone" (click)="selectReport(report)">●</button></div><div *ngIf="currentView !== 'mapa'" class="panel full-table"><div class="table-wrap"><table><thead><tr><th>REPORTE</th><th>CATEGORÍA</th><th>ZONA</th><th>PRIORIDAD</th><th>ESTADO</th><th>RESPONSABLE</th><th></th></tr></thead><tbody><tr *ngFor="let report of filteredReports" (click)="selectReport(report)"><td><div class="report-name"><span class="report-id">{{ report.id }}</span><b>{{ report.title }}</b><small>Hace {{ report.age }}</small></div></td><td><span class="category"><i [class]="'cat-' + report.tone"></i>{{ report.category }}</span></td><td>{{ report.zone }}</td><td><span class="priority-tag" [class]="'priority-' + report.tone">{{ report.priority }}</span></td><td><span class="status-tag" [class]="statusClass(report.status)"><i></i>{{ report.status }}</span></td><td><span class="owner"><span class="mini-avatar">{{ initials(report.owner) }}</span>{{ report.owner }}</span></td><td><span class="row-more">•••</span></td></tr></tbody></table></div></div></section>
          </ng-container>
        </section>
      </main>

      <aside *ngIf="selectedReport" class="detail-drawer"><button class="close-drawer" (click)="selectedReport = null">×</button><div class="drawer-cover"><span class="cover-pin">⌖</span><span class="cover-code">{{ selectedReport.id }}</span></div><div class="drawer-body"><div class="drawer-heading"><div><span class="status-tag" [class]="statusClass(selectedReport.status)"><i></i>{{ selectedReport.status }}</span><h2>{{ selectedReport.title }}</h2><p>{{ selectedReport.category }} · {{ selectedReport.zone }}</p></div></div><div class="drawer-actions"><button class="primary-button small" (click)="showToast('Reporte delegado a ' + selectedReport.owner)">Delegar reporte</button><button class="outline-button small" (click)="cycleStatus()">Cambiar estado</button></div><div class="detail-section"><h3>Información del reporte</h3><dl><div><dt>Prioridad</dt><dd><span class="priority-tag" [class]="'priority-' + selectedReport.tone">{{ selectedReport.priority }}</span></dd></div><div><dt>Responsable</dt><dd class="owner"><span class="mini-avatar">{{ initials(selectedReport.owner) }}</span>{{ selectedReport.owner }}</dd></div><div><dt>Creado</dt><dd>Hace {{ selectedReport.age }}</dd></div><div><dt>Seguimiento</dt><dd class="tracking">MU-{{ selectedReport.id.replace('RP-', '') }}</dd></div></dl></div><div class="detail-section"><h3>Actividad</h3><div class="timeline"><div><i class="timeline-dot teal"></i><p><b>Reporte actualizado</b><small>Hoy, 10:42 · María González</small></p></div><div><i class="timeline-dot amber"></i><p><b>Prioridad modificada a {{ selectedReport.priority }}</b><small>Ayer, 16:20 · Sistema</small></p></div><div><i class="timeline-dot gray"></i><p><b>Reporte recibido</b><small>{{ selectedReport.age }} · Vecino</small></p></div></div></div><div class="drawer-note"><span>✦</span><p>Las notas internas solo son visibles para el equipo municipal.</p></div></div></aside>
      <div *ngIf="toast" class="toast">✓ {{ toast }}</div>
    </div>
  `,
  styles: []
})
export class AppComponent {
  sidebarCollapsed = false; mobileMenuOpen = false; currentView: ViewKey = 'dashboard'; selectedReport: Report | null = null; searchTerm = ''; toast = '';
  navItems: { key: ViewKey; label: string; icon: string; badge?: string }[] = [
    { key: 'dashboard', label: 'Dashboard', icon: '◒' }, { key: 'mapa', label: 'Mapa general', icon: '⌖' }, { key: 'reportes', label: 'Reportes', icon: '▤', badge: '248' }, { key: 'delegacion', label: 'Delegación', icon: '⇄', badge: '37' }, { key: 'prioridades', label: 'Prioridades', icon: '⚑', badge: '12' }, { key: 'estadisticas', label: 'Estadísticas', icon: '▥' }, { key: 'configuracion', label: 'Configuración', icon: '⚙' }, { key: 'auditoria', label: 'Auditoría', icon: '◷' }
  ];
  reports: Report[] = [
    { id: 'RP-1048', title: 'Bache profundo en calzada', category: 'Vialidad', zone: 'Centro', priority: 'Crítica', status: 'Pendiente', owner: 'Sin asignar', age: '24 min', tone: 'critical', x: 35, y: 44 },
    { id: 'RP-1045', title: 'Luminaria sin funcionar', category: 'Alumbrado', zone: 'Godoy Cruz', priority: 'Alta', status: 'En proceso', owner: 'Obras Públicas', age: '1 h', tone: 'high', x: 67, y: 31 },
    { id: 'RP-1042', title: 'Acumulación de residuos', category: 'Higiene urbana', zone: 'Ciudad', priority: 'Media', status: 'En proceso', owner: 'Servicios Urbanos', age: '3 h', tone: 'normal', x: 51, y: 61 },
    { id: 'RP-1039', title: 'Vereda rota frente a escuela', category: 'Espacio público', zone: 'Las Heras', priority: 'Alta', status: 'Pendiente', owner: 'Sin asignar', age: '5 h', tone: 'high', x: 23, y: 25 },
    { id: 'RP-1036', title: 'Semáforo intermitente', category: 'Tránsito', zone: 'Sexta Sección', priority: 'Crítica', status: 'En proceso', owner: 'Tránsito', age: '7 h', tone: 'critical', x: 77, y: 68 },
    { id: 'RP-1030', title: 'Poda pendiente', category: 'Arbolado', zone: 'Quinta Sección', priority: 'Baja', status: 'Resuelto', owner: 'Parques y Paseos', age: '1 d', tone: 'normal', x: 81, y: 48 }
  ];
  get activeLabel(): string { return this.navItems.find(item => item.key === this.currentView)?.label ?? 'Dashboard'; }
  get activeTitle(): string { return this.currentView === 'dashboard' ? 'Resumen operativo' : this.activeLabel; }
  get priorityReports(): Report[] { return this.reports.filter(r => r.priority === 'Crítica' || r.priority === 'Alta').slice(0, 3); }
  get filteredReports(): Report[] { const query = this.searchTerm.toLowerCase().trim(); return this.reports.filter(r => !query || `${r.title} ${r.category} ${r.zone} ${r.owner}`.toLowerCase().includes(query)); }
  setView(view: ViewKey): void { this.currentView = view; this.selectedReport = null; this.mobileMenuOpen = false; }
  selectReport(report: Report): void { this.selectedReport = report; }
  statusClass(status: Status): string { return status === 'Pendiente' ? 'status-pending' : status === 'En proceso' ? 'status-progress' : 'status-resolved'; }
  initials(name: string): string { return name === 'Sin asignar' ? '—' : name.split(' ').map(part => part[0]).join('').slice(0, 2); }
  cycleStatus(): void { if (!this.selectedReport) return; const next: Status = this.selectedReport.status === 'Pendiente' ? 'En proceso' : this.selectedReport.status === 'En proceso' ? 'Resuelto' : 'Pendiente'; this.selectedReport.status = next; this.showToast(`Estado cambiado a ${next}`); }
  showToast(message: string): void { this.toast = message; window.setTimeout(() => this.toast = '', 2600); }
}
