import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'mu-delegation-preview', standalone: true, imports: [CommonModule],
  template: `
    <div class="feature-toolbar"><div><b>Equipos municipales</b><span>Carga operativa y asignaciones actuales</span></div><button class="primary-button compact">＋ Crear equipo</button></div>
    <div class="team-grid">
      <article *ngFor="let team of teams" class="team-card"><div class="team-head"><span class="team-avatar" [style.background]="team.color">{{team.initials}}</span><div><b>{{team.name}}</b><span>{{team.people}} integrantes</span></div><button>•••</button></div><div class="load-row"><span>Carga de trabajo</span><strong>{{team.load}}%</strong></div><div class="load-track"><i [style.width.%]="team.load" [class.overload]="team.load > 80"></i></div><div class="team-stats"><span><b>{{team.active}}</b> activos</span><span><b>{{team.urgent}}</b> urgentes</span><span><b>{{team.resolved}}</b> resueltos</span></div></article>
    </div>
    <article class="panel assignment-queue"><div class="panel-header"><div><h2>Bandeja sin asignar</h2><p>37 reportes esperan una delegación responsable</p></div><button class="ghost-button">Asignación automática</button></div><div class="assignment-list"><div *ngFor="let item of queue" class="assignment-row"><span class="queue-priority" [class.critical]="item.priority==='Crítica'"></span><div><b>{{item.title}}</b><small>{{item.id}} · {{item.zone}} · Hace {{item.age}}</small></div><span class="priority-tag" [class.priority-critical]="item.priority==='Crítica'" [class.priority-high]="item.priority==='Alta'">{{item.priority}}</span><select aria-label="Seleccionar equipo"><option>Seleccionar equipo…</option><option>Obras Públicas</option><option>Servicios Urbanos</option><option>Tránsito</option></select><button class="assign-button">Asignar</button></div></div></article>
  `
})
export class DelegationPreviewComponent {
  teams=[{name:'Obras Públicas',initials:'OP',people:8,load:78,active:42,urgent:5,resolved:18,color:'#325e82'},{name:'Servicios Urbanos',initials:'SU',people:12,load:91,active:68,urgent:8,resolved:31,color:'#138f87'},{name:'Tránsito',initials:'TR',people:6,load:56,active:27,urgent:3,resolved:22,color:'#d89220'},{name:'Parques y Paseos',initials:'PP',people:9,load:64,active:34,urgent:1,resolved:16,color:'#638f59'}];
  queue=[{id:'RP-1048',title:'Bache profundo en calzada',zone:'Centro',age:'24 min',priority:'Crítica'},{id:'RP-1039',title:'Vereda rota frente a escuela',zone:'Las Heras',age:'5 h',priority:'Alta'},{id:'RP-1028',title:'Contenedor desbordado',zone:'Cuarta Sección',age:'9 h',priority:'Alta'}];
}

@Component({
  selector: 'mu-priorities-preview', standalone: true, imports: [CommonModule],
  template: `
    <div class="feature-toolbar"><div><b>Matriz de prioridades</b><span>Ordenada por impacto, urgencia y antigüedad</span></div><div class="toolbar-actions"><button class="ghost-button">Configurar reglas</button><button class="primary-button compact">＋ Nueva regla</button></div></div>
    <div class="priority-board"><section *ngFor="let lane of lanes" class="priority-lane"><header><div><i [style.background]="lane.color"></i><b>{{lane.name}}</b><span>{{lane.items.length}}</span></div><small>{{lane.description}}</small></header><article *ngFor="let item of lane.items" class="issue-card"><div class="issue-meta"><span>{{item.id}}</span><span>•••</span></div><h3>{{item.title}}</h3><p>{{item.category}} · {{item.zone}}</p><div class="issue-footer"><span class="mini-avatar">{{item.owner}}</span><small>{{item.time}}</small></div></article><button class="lane-more">Ver todos los reportes →</button></section></div>
  `
})
export class PrioritiesPreviewComponent {
  lanes=[{name:'Crítica',color:'#d85d52',description:'Atención inmediata · 0–4 h',items:[{id:'RP-1048',title:'Bache profundo en calzada',category:'Vialidad',zone:'Centro',owner:'—',time:'Hace 24 min'},{id:'RP-1036',title:'Semáforo intermitente',category:'Tránsito',zone:'Sexta Sección',owner:'TR',time:'Hace 7 h'}]},{name:'Alta',color:'#d89220',description:'Resolver dentro de 24 h',items:[{id:'RP-1045',title:'Luminaria sin funcionar',category:'Alumbrado',zone:'Godoy Cruz',owner:'OP',time:'Hace 1 h'},{id:'RP-1039',title:'Vereda rota frente a escuela',category:'Espacio público',zone:'Las Heras',owner:'—',time:'Hace 5 h'}]},{name:'Media',color:'#0b8f87',description:'Resolver dentro de 72 h',items:[{id:'RP-1042',title:'Acumulación de residuos',category:'Higiene urbana',zone:'Ciudad',owner:'SU',time:'Hace 3 h'},{id:'RP-1024',title:'Cartel dañado',category:'Espacio público',zone:'Centro',owner:'OP',time:'Hace 12 h'}]},{name:'Baja',color:'#7d8b96',description:'Programable',items:[{id:'RP-1030',title:'Poda pendiente',category:'Arbolado',zone:'Quinta Sección',owner:'PP',time:'Hace 1 d'}]}];
}

@Component({
  selector: 'mu-statistics-preview', standalone: true, imports: [CommonModule],
  template: `
    <div class="feature-toolbar"><div><b>Rendimiento operativo</b><span>Indicadores de los últimos 12 meses</span></div><button class="ghost-button">Descargar informe ↓</button></div>
    <div class="analytics-kpis"><article><span>Tiempo medio de atención</span><b>3 h 42 min</b><small class="positive">↓ 18% este mes</small></article><article><span>Tasa de resolución</span><b>82,6%</b><small class="positive">↑ 6,4% este mes</small></article><article><span>Cumplimiento de SLA</span><b>91,2%</b><small class="positive">↑ 3,1% este mes</small></article></div>
    <div class="analytics-grid"><article class="panel chart-panel"><div class="panel-header"><div><h2>Reportes recibidos y resueltos</h2><p>Evolución mensual</p></div><div class="chart-legend"><span><i></i>Recibidos</span><span><i></i>Resueltos</span></div></div><div class="line-chart"><svg viewBox="0 0 700 250" preserveAspectRatio="none" aria-label="Gráfico de evolución"><g class="grid-lines"><line *ngFor="let y of [40,90,140,190,240]" x1="0" [attr.y1]="y" x2="700" [attr.y2]="y"></line></g><polyline points="0,190 65,165 128,174 190,130 255,145 320,96 385,115 450,84 515,104 580,62 640,77 700,40" class="received"></polyline><polyline points="0,220 65,200 128,188 190,170 255,165 320,142 385,132 450,118 515,128 580,98 640,90 700,70" class="resolved"></polyline></svg><div class="month-labels"><span *ngFor="let m of months">{{m}}</span></div></div></article><article class="panel category-panel"><div class="panel-header"><div><h2>Por categoría</h2><p>Distribución actual</p></div></div><div class="donut"><div class="donut-center"><b>248</b><span>activos</span></div></div><div class="category-breakdown"><div *ngFor="let c of categories"><span><i [style.background]="c.color"></i>{{c.name}}</span><b>{{c.value}}%</b></div></div></article></div>
  `
})
export class StatisticsPreviewComponent { months=['Sep','Oct','Nov','Dic','Ene','Feb','Mar','Abr','May','Jun','Jul','Ago']; categories=[{name:'Vialidad',value:31,color:'#d85d52'},{name:'Alumbrado',value:24,color:'#d89220'},{name:'Higiene urbana',value:21,color:'#0b8f87'},{name:'Otros',value:24,color:'#6681a1'}]; }

@Component({
  selector: 'mu-settings-preview', standalone: true, imports: [CommonModule],
  template: `
    <div class="settings-layout"><nav class="settings-nav"><button class="active">General</button><button>Categorías</button><button>Estados y prioridades</button><button>Equipos y usuarios</button><button>Notificaciones</button><button>Seguridad</button></nav><section class="panel settings-panel"><div class="settings-heading"><div><h2>Configuración general</h2><p>Parámetros de operación de Mapa Urbano</p></div><button class="primary-button compact">Guardar cambios</button></div><div class="form-section"><h3>Información de la organización</h3><div class="form-grid"><label>Nombre visible<input value="Municipalidad de Mendoza"></label><label>Zona horaria<select><option>America/Argentina/Mendoza</option></select></label><label>Correo de contacto<input value="operaciones@municipio.gob.ar"></label><label>Idioma<select><option>Español (Argentina)</option></select></label></div></div><div class="form-section"><h3>Reglas operativas</h3><div class="setting-row"><div><b>Asignación automática</b><p>Sugerir equipos según categoría y zona del reporte.</p></div><button class="toggle on" aria-label="Asignación automática activada"><i></i></button></div><div class="setting-row"><div><b>Alertas de vencimiento</b><p>Notificar a supervisores cuando un SLA esté próximo a vencer.</p></div><button class="toggle on" aria-label="Alertas activadas"><i></i></button></div><div class="setting-row"><div><b>Publicación inmediata</b><p>Mostrar automáticamente nuevos reportes en el mapa público.</p></div><button class="toggle" aria-label="Publicación inmediata desactivada"><i></i></button></div></div></section></div>
  `
})
export class SettingsPreviewComponent {}

@Component({
  selector: 'mu-audit-preview', standalone: true, imports: [CommonModule],
  template: `
    <div class="feature-toolbar"><div><b>Registro de actividad</b><span>Trazabilidad completa de acciones administrativas</span></div><button class="ghost-button">Exportar registro ↓</button></div><article class="panel audit-panel"><div class="audit-filter"><div class="search-field">⌕ <input placeholder="Buscar por usuario, reporte o acción"></div><button class="filter-button">Hoy</button><button class="filter-button">Todas las acciones</button></div><div class="audit-list"><div *ngFor="let event of events" class="audit-row"><span class="audit-icon" [class]="event.tone">{{event.icon}}</span><div class="audit-copy"><b>{{event.action}}</b><p>{{event.detail}}</p></div><div class="audit-user"><span class="mini-avatar">{{event.initials}}</span><div><b>{{event.user}}</b><small>{{event.role}}</small></div></div><time>{{event.time}}</time><button>•••</button></div></div><footer class="audit-footer">Mostrando 6 de 1.284 eventos <button>Siguiente →</button></footer></article>
  `
})
export class AuditPreviewComponent { events=[{icon:'↻',tone:'blue',action:'Estado de reporte actualizado',detail:'RP-1045 · Pendiente → En proceso',initials:'MG',user:'María González',role:'Supervisora',time:'10:42'},{icon:'⇄',tone:'teal',action:'Reporte delegado',detail:'RP-1042 asignado a Servicios Urbanos',initials:'JL',user:'Juan López',role:'Operador',time:'10:18'},{icon:'⚑',tone:'amber',action:'Prioridad modificada',detail:'RP-1039 · Media → Alta',initials:'MG',user:'María González',role:'Supervisora',time:'09:56'},{icon:'＋',tone:'green',action:'Categoría creada',detail:'Nueva categoría “Señalización”',initials:'AS',user:'Ana Suárez',role:'Administradora',time:'09:31'},{icon:'✓',tone:'teal',action:'Reporte resuelto',detail:'RP-1030 · Poda pendiente',initials:'PP',user:'Parques y Paseos',role:'Equipo',time:'08:47'},{icon:'□',tone:'gray',action:'Sesión iniciada',detail:'Acceso correcto desde red municipal',initials:'MG',user:'María González',role:'Supervisora',time:'08:15'}]; }
